FROM hvalev/shiny-server-arm:devtools-R4.3.3-S1.5.21.1012
# install plotly first as otherwise it triggers errors
RUN R -e "install.packages('plotly', repos='http://cran.rstudio.com/', type='source')"
# gdal-config needed for terra and raster R packages or they won't compile
RUN apt-get update && apt-get install libgdal-dev -y
# important for rpy2
RUN apt-get update && apt-get install nano python3-dev python3.11-venv -y
COPY . /tests
RUN R -e "devtools::install('/tests/rcicr', repos='http://cran.rstudio.com/')"
RUN bash /tests/setup_env.sh
RUN bash /tests/setup_pyenv.sh
# reset the entrypoint from the base image, as we don't need shiny just the R env and devtools
ENTRYPOINT []